import RAM, * as $RAM from '@alicloud/ram20150501';
import * as $OpenApi from '@alicloud/openapi-client';
import type { AuthConfig } from '../utils/config';
import { resolveSdkCtor } from '../utils/sdk';

const RamClientCtor = resolveSdkCtor<RAM>(RAM, '@alicloud/ram20150501');

const DEFAULT_BOOTSTRAP_USER = 'licell-operator';
const DEFAULT_BOOTSTRAP_POLICY = 'LicellOperatorPolicy';
const RAM_USER_PATTERN = /^[A-Za-z0-9._-]{1,64}$/;
const RAM_POLICY_PATTERN = /^[A-Za-z0-9-]{1,128}$/;

export const LICELL_POLICY_ACTIONS = [
  'fc:*',
  'rds:*',
  'kvstore:*',
  'oss:*',
  'alidns:*',
  'vpc:*',
  'ecs:*',
  'cr:*',
  'log:*',
  'cdn:*'
] as const;

export interface BootstrapRamAccessInput {
  adminAuth: AuthConfig;
  userName?: string;
  policyName?: string;
}

export interface BootstrapRamAccessResult {
  userName: string;
  policyName: string;
  accessKeyId: string;
  accessKeySecret: string;
  createdUser: boolean;
  createdPolicy: boolean;
}

export function normalizeRamUserName(input?: string) {
  const value = (input || DEFAULT_BOOTSTRAP_USER).trim();
  if (!RAM_USER_PATTERN.test(value)) {
    throw new Error('bootstrap RAM 用户名不合法：仅支持字母、数字、点、短横线、下划线，长度 1-64');
  }
  return value;
}

export function normalizeRamPolicyName(input?: string) {
  const value = (input || DEFAULT_BOOTSTRAP_POLICY).trim();
  if (!RAM_POLICY_PATTERN.test(value)) {
    throw new Error('bootstrap RAM 策略名不合法：仅支持字母、数字、短横线，长度 1-128');
  }
  return value;
}

export function buildLicellPolicyDocument() {
  return JSON.stringify({
    Version: '1',
    Statement: [
      {
        Effect: 'Allow',
        Action: [...LICELL_POLICY_ACTIONS],
        Resource: '*'
      }
    ]
  });
}

function createRamClient(adminAuth: AuthConfig) {
  return new RamClientCtor(new $OpenApi.Config({
    accessKeyId: adminAuth.ak,
    accessKeySecret: adminAuth.sk,
    endpoint: 'ram.aliyuncs.com'
  }));
}

function getErrorCode(err: unknown) {
  if (typeof err !== 'object' || err === null) return '';
  if (!('code' in err)) return '';
  return String((err as { code?: unknown }).code || '');
}

function getErrorMessage(err: unknown) {
  if (typeof err !== 'object' || err === null) return '';
  if (!('message' in err)) return '';
  return String((err as { message?: unknown }).message || '');
}

function isEntityNotExistError(err: unknown) {
  const code = getErrorCode(err);
  const message = getErrorMessage(err).toLowerCase();
  return code.includes('EntityNotExist') || message.includes('not exist');
}

function isAlreadyExistsError(err: unknown) {
  const code = getErrorCode(err);
  const message = getErrorMessage(err).toLowerCase();
  return code.includes('EntityAlreadyExists')
    || code.includes('EntityAlreadyExist')
    || message.includes('already exists')
    || message.includes('already attached');
}

async function ensureRamUser(client: RAM, userName: string) {
  try {
    await client.getUser(new $RAM.GetUserRequest({ userName }));
    return { created: false };
  } catch (err: unknown) {
    if (!isEntityNotExistError(err)) throw err;
  }

  await client.createUser(new $RAM.CreateUserRequest({
    userName,
    displayName: userName,
    comments: 'Managed by licell bootstrap login'
  }));
  return { created: true };
}

async function ensureCustomPolicy(client: RAM, policyName: string) {
  try {
    await client.getPolicy(new $RAM.GetPolicyRequest({ policyType: 'Custom', policyName }));
    return { created: false };
  } catch (err: unknown) {
    if (!isEntityNotExistError(err)) throw err;
  }

  await client.createPolicy(new $RAM.CreatePolicyRequest({
    policyName,
    description: 'Least-privilege policy generated by licell bootstrap login',
    policyDocument: buildLicellPolicyDocument()
  }));
  return { created: true };
}

async function ensurePolicyAttachedToUser(client: RAM, policyName: string, userName: string) {
  try {
    await client.attachPolicyToUser(new $RAM.AttachPolicyToUserRequest({
      policyType: 'Custom',
      policyName,
      userName
    }));
  } catch (err: unknown) {
    if (isAlreadyExistsError(err)) return;
    throw err;
  }
}

async function createRamAccessKey(client: RAM, userName: string) {
  const listed = await client.listAccessKeys(new $RAM.ListAccessKeysRequest({ userName }));
  const keys = listed.body?.accessKeys?.accessKey || [];
  const activeCount = keys.filter((key) => key.status === 'Active').length;
  if (activeCount >= 2) {
    throw new Error(`RAM 用户 ${userName} 的 AccessKey 已达到上限（2 个）。请先在控制台删除旧 key 后重试。`);
  }

  const created = await client.createAccessKey(new $RAM.CreateAccessKeyRequest({ userName }));
  const accessKeyId = created.body?.accessKey?.accessKeyId;
  const accessKeySecret = created.body?.accessKey?.accessKeySecret;
  if (!accessKeyId || !accessKeySecret) {
    throw new Error('创建 RAM AccessKey 成功但返回字段不完整，请重试');
  }
  return { accessKeyId, accessKeySecret };
}

export async function bootstrapLicellRamAccess(input: BootstrapRamAccessInput): Promise<BootstrapRamAccessResult> {
  const userName = normalizeRamUserName(input.userName);
  const policyName = normalizeRamPolicyName(input.policyName);
  const client = createRamClient(input.adminAuth);

  const userResult = await ensureRamUser(client, userName);
  const policyResult = await ensureCustomPolicy(client, policyName);
  await ensurePolicyAttachedToUser(client, policyName, userName);
  const key = await createRamAccessKey(client, userName);

  return {
    userName,
    policyName,
    accessKeyId: key.accessKeyId,
    accessKeySecret: key.accessKeySecret,
    createdUser: userResult.created,
    createdPolicy: policyResult.created
  };
}
